export const links = {
  "Two Sum": "https://leetcode.com/problems/two-sum/",
  "Valid Parentheses": "https://leetcode.com/problems/valid-parentheses/",
  "Merge Two Sorted Lists": "https://leetcode.com/problems/merge-two-sorted-lists/",
  "Best Time to Buy and Sell Stock": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  "Valid Palindrome": "https://leetcode.com/problems/valid-palindrome/",
  "Maximum Subarray": "https://leetcode.com/problems/maximum-subarray/",
  "Climbing Stairs": "https://leetcode.com/problems/climbing-stairs/",
  "Binary Tree Inorder Traversal": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
  "Same Tree": "https://leetcode.com/problems/same-tree/",
  "Valid Anagram": "https://leetcode.com/problems/valid-anagram/",
  "Missing Number": "https://leetcode.com/problems/missing-number/",
  "Move Zeroes": "https://leetcode.com/problems/move-zeroes/",
  "First Bad Version": "https://leetcode.com/problems/first-bad-version/",
  "Reverse Linked List": "https://leetcode.com/problems/reverse-linked-list/",
  "Contains Duplicate": "https://leetcode.com/problems/contains-duplicate/",
  "Palindrome Number": "https://leetcode.com/problems/palindrome-number/",
  "Roman to Integer": "https://leetcode.com/problems/roman-to-integer/",
  "Longest Common Prefix": "https://leetcode.com/problems/longest-common-prefix/",
  "Remove Duplicates from Sorted Array": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
  "Remove Element": "https://leetcode.com/problems/remove-element/",
  "Search Insert Position": "https://leetcode.com/problems/search-insert-position/",
  "Length of Last Word": "https://leetcode.com/problems/length-of-last-word/",
  "Plus One": "https://leetcode.com/problems/plus-one/",
  "Add Binary": "https://leetcode.com/problems/add-binary/",
  "Sqrt(x)": "https://leetcode.com/problems/sqrtx/",
  "Merge Sorted Array": "https://leetcode.com/problems/merge-sorted-array/",
  "Binary Tree Preorder Traversal": "https://leetcode.com/problems/binary-tree-preorder-traversal/",
  "Binary Tree Postorder Traversal": "https://leetcode.com/problems/binary-tree-postorder-traversal/",
  "Linked List Cycle": "https://leetcode.com/problems/linked-list-cycle/",
  "Min Stack": "https://leetcode.com/problems/min-stack/",
  "Intersection of Two Linked Lists": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
  "Excel Sheet Column Number": "https://leetcode.com/problems/excel-sheet-column-number/",
  "Majority Element": "https://leetcode.com/problems/majority-element/",
  "Excel Sheet Column Title": "https://leetcode.com/problems/excel-sheet-column-title/",
  "Factorial Trailing Zeroes": "https://leetcode.com/problems/factorial-trailing-zeroes/",
  "Happy Number": "https://leetcode.com/problems/happy-number/",
  "Remove Linked List Elements": "https://leetcode.com/problems/remove-linked-list-elements/",
  "Count Primes": "https://leetcode.com/problems/count-primes/",
  "Isomorphic Strings": "https://leetcode.com/problems/isomorphic-strings/",
  "Reverse Bits": "https://leetcode.com/problems/reverse-bits/",
  "Number of 1 Bits": "https://leetcode.com/problems/number-of-1-bits/",
  "House Robber": "https://leetcode.com/problems/house-robber/",
  "Summary Ranges": "https://leetcode.com/problems/summary-ranges/",
  "Power of Two": "https://leetcode.com/problems/power-of-two/",
  "Implement Queue using Stacks": "https://leetcode.com/problems/implement-queue-using-stacks/",
  "Implement Stack using Queues": "https://leetcode.com/problems/implement-stack-using-queues/",
  "Invert Binary Tree": "https://leetcode.com/problems/invert-binary-tree/",
  "Delete Node in a Linked List": "https://leetcode.com/problems/delete-node-in-a-linked-list/",
  "Lowest Common Ancestor of a Binary Search Tree": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
  "Single Number": "https://leetcode.com/problems/single-number/",
  "Pascal's Triangle": "https://leetcode.com/problems/pascals-triangle/",
  "Pascal's Triangle II": "https://leetcode.com/problems/pascals-triangle-ii/",
  "Valid Perfect Square": "https://leetcode.com/problems/valid-perfect-square/",
  "Guess Number Higher or Lower": "https://leetcode.com/problems/guess-number-higher-or-lower/",
  "Ransom Note": "https://leetcode.com/problems/ransom-note/",
  "First Unique Character in a String": "https://leetcode.com/problems/first-unique-character-in-a-string/",
  "Find the Difference": "https://leetcode.com/problems/find-the-difference/",
  "Is Subsequence": "https://leetcode.com/problems/is-subsequence/",
  "Binary Watch": "https://leetcode.com/problems/binary-watch/",
  "Sum of Left Leaves": "https://leetcode.com/problems/sum-of-left-leaves/",
  "Convert a Number to Hexadecimal": "https://leetcode.com/problems/convert-a-number-to-hexadecimal/",
  "Queue Reconstruction by Height": "https://leetcode.com/problems/queue-reconstruction-by-height/",
  "Third Maximum Number": "https://leetcode.com/problems/third-maximum-number/",
  "Add Strings": "https://leetcode.com/problems/add-strings/",
  "Number of Segments in a String": "https://leetcode.com/problems/number-of-segments-in-a-string/",
  "Path Sum III": "https://leetcode.com/problems/path-sum-iii/",
  "Arranging Coins": "https://leetcode.com/problems/arranging-coins/",
  "Find All Numbers Disappeared in an Array": "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
  "Assign Cookies": "https://leetcode.com/problems/assign-cookies/",
  "Repeated Substring Pattern": "https://leetcode.com/problems/repeated-substring-pattern/",
  "Hamming Distance": "https://leetcode.com/problems/hamming-distance/",
  "Island Perimeter": "https://leetcode.com/problems/island-perimeter/",
  "Number Complement": "https://leetcode.com/problems/number-complement/",
  "License Key Formatting": "https://leetcode.com/problems/license-key-formatting/",
  "Max Consecutive Ones": "https://leetcode.com/problems/max-consecutive-ones/",
  "Construct the Rectangle": "https://leetcode.com/problems/construct-the-rectangle/",
  "Next Greater Element I": "https://leetcode.com/problems/next-greater-element-i/",
  "Keyboard Row": "https://leetcode.com/problems/keyboard-row/",
  "Find Mode in Binary Search Tree": "https://leetcode.com/problems/find-mode-in-binary-search-tree/",
  "Base 7": "https://leetcode.com/problems/base-7/",
  "Perfect Number": "https://leetcode.com/problems/perfect-number/",
  "Fibonacci Number": "https://leetcode.com/problems/fibonacci-number/",
  "Detect Capital": "https://leetcode.com/problems/detect-capital/",
  "Longest Uncommon Subsequence I": "https://leetcode.com/problems/longest-uncommon-subsequence-i/",
  "Binary Tree Tilt": "https://leetcode.com/problems/binary-tree-tilt/",
  "Array Partition I": "https://leetcode.com/problems/array-partition-i/",
  "Reverse String": "https://leetcode.com/problems/reverse-string/",
  "Reverse Vowels of a String": "https://leetcode.com/problems/reverse-vowels-of-a-string/",
  "Intersection of Two Arrays": "https://leetcode.com/problems/intersection-of-two-arrays/",
  "Intersection of Two Arrays II": "https://leetcode.com/problems/intersection-of-two-arrays-ii/",
  "Power of Three": "https://leetcode.com/problems/power-of-three/",
  "Power of Four": "https://leetcode.com/problems/power-of-four/",
  "Reverse String II": "https://leetcode.com/problems/reverse-string-ii/",
  "Student Attendance Record I": "https://leetcode.com/problems/student-attendance-record-i/",
  "Reshape the Matrix": "https://leetcode.com/problems/reshape-the-matrix/",
  "Subtree of Another Tree": "https://leetcode.com/problems/subtree-of-another-tree/",
  "Shortest Unsorted Continuous Subarray": "https://leetcode.com/problems/shortest-unsorted-continuous-subarray/",
  "Can Place Flowers": "https://leetcode.com/problems/can-place-flowers/",
  "Maximum Average Subarray I": "https://leetcode.com/problems/maximum-average-subarray-i/",
  "Set Mismatch": "https://leetcode.com/problems/set-mismatch/",
  "Two Sum IV - Input is a BST": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
  "Judge Route Circle": "https://leetcode.com/problems/judge-route-circle/",
  "Baseball Game": "https://leetcode.com/problems/baseball-game/",
  "Valid Palindrome II": "https://leetcode.com/problems/valid-palindrome-ii/",
  "Calorie Food Input Stream": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
  "Binary Number with Alternating Bits": "https://leetcode.com/problems/binary-number-with-alternating-bits/",
  "Search in a Binary Search Tree": "https://leetcode.com/problems/search-in-a-binary-search-tree/",
  "Insert into a Binary Search Tree": "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
  "Redundant Connection": "https://leetcode.com/problems/redundant-connection/",
  "Degree of an Array": "https://leetcode.com/problems/degree-of-an-array/",
  "Binary Search": "https://leetcode.com/problems/binary-search/",
  "Design HashSet": "https://leetcode.com/problems/design-hashset/",
  "Design HashMap": "https://leetcode.com/problems/design-hashmap/",
  "To Lower Case": "https://leetcode.com/problems/to-lower-case/",
  "1-bit and 2-bit Characters": "https://leetcode.com/problems/1-bit-and-2-bit-characters/",
  "Find Pivot Index": "https://leetcode.com/problems/find-pivot-index/",
  "Min Cost Climbing Stairs": "https://leetcode.com/problems/min-cost-climbing-stairs/",
  "Largest Number At Least Twice of Others": "https://leetcode.com/problems/largest-number-at-least-twice-of-others/",
  "Shortest Completing Word": "https://leetcode.com/problems/shortest-completing-word/",
  "Prime Number of Set Bits in Binary Representation": "https://leetcode.com/problems/prime-number-of-set-bits-in-binary-representation/",
  "Jewels and Stones": "https://leetcode.com/problems/jewels-and-stones/",
  "Toeplitz Matrix": "https://leetcode.com/problems/toeplitz-matrix/",
  "Rotate String": "https://leetcode.com/problems/rotate-string/",
  "Unique Morse Code Words": "https://leetcode.com/problems/unique-morse-code-words/",
  "Number of Lines To Write String": "https://leetcode.com/problems/number-of-lines-to-write-string/",
  "Largest Triangle Area": "https://leetcode.com/problems/largest-triangle-area/",
  "Most Common Word": "https://leetcode.com/problems/most-common-word/",
  "Goat Latin": "https://leetcode.com/problems/goat-latin/",
  "Backspace String Compare": "https://leetcode.com/problems/backspace-string-compare/",
  "Peak Index in a Mountain Array": "https://leetcode.com/problems/peak-index-in-a-mountain-array/",
  "Buddy Strings": "https://leetcode.com/problems/buddy-strings/",
  "Lemonade Change": "https://leetcode.com/problems/lemonade-change/",
  "Rectangle Overlap": "https://leetcode.com/problems/rectangle-overlap/",
  "Binary Gap": "https://leetcode.com/problems/binary-gap/",
  "Transpose Matrix": "https://leetcode.com/problems/transpose-matrix/",
  "Monotonic Array": "https://leetcode.com/problems/monotonic-array/",
  "Uncommon Words from Two Sentences": "https://leetcode.com/problems/uncommon-words-from-two-sentences/",
  "Projection Area of 3D Shapes": "https://leetcode.com/problems/projection-area-of-3d-shapes/",
  "Leaf-Similar Trees": "https://leetcode.com/problems/leaf-similar-trees/",
  "Middle of the Linked List": "https://leetcode.com/problems/middle-of-the-linked-list/",
  "Walking Robot Simulation": "https://leetcode.com/problems/walking-robot-simulation/",
  "Surface Area of 3D Shapes": "https://leetcode.com/problems/surface-area-of-3d-shapes/",
  "Score of Parentheses": "https://leetcode.com/problems/score-of-parentheses/",
  "Hand of Straights": "https://leetcode.com/problems/hand-of-straights/",
  "Fair Candy Swap": "https://leetcode.com/problems/fair-candy-swap/",
  "Sort Array By Parity": "https://leetcode.com/problems/sort-array-by-parity/",
  "Sort Array By Parity II": "https://leetcode.com/problems/sort-array-by-parity-ii/",
  "Long Pressed Name": "https://leetcode.com/problems/long-pressed-name/",
  "Verifying an Alien Dictionary": "https://leetcode.com/problems/verifying-an-alien-dictionary/",
  "Univalued Binary Tree": "https://leetcode.com/problems/univalued-binary-tree/",
  "N-Repeated Element in Size 2N Array": "https://leetcode.com/problems/n-repeated-element-in-size-2n-array/",
  "Find Common Characters": "https://leetcode.com/problems/find-common-characters/",
  "Complement of Base 10 Integer": "https://leetcode.com/problems/complement-of-base-10-integer/",
  "Pairs of Songs With Total Durations Divisible by 60": "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/",
  "Available Captures for Rook": "https://leetcode.com/problems/available-captures-for-rook/",
  "Squares of a Sorted Array": "https://leetcode.com/problems/squares-of-a-sorted-array/",
  "Interval List Intersections": "https://leetcode.com/problems/interval-list-intersections/",
  "Add to Array-Form of Integer": "https://leetcode.com/problems/add-to-array-form-of-integer/",
  "Maximum Binary Tree": "https://leetcode.com/problems/maximum-binary-tree/",
  "Flood Fill": "https://leetcode.com/problems/flood-fill/",
  "Network Delay Time": "https://leetcode.com/problems/network-delay-time/",
  "Delete Node in a BST": "https://leetcode.com/problems/delete-node-in-a-bst/",
  "Minimum Absolute Difference in BST": "https://leetcode.com/problems/minimum-absolute-difference-in-bst/",
  "Convert BST to Greater Tree": "https://leetcode.com/problems/convert-bst-to-greater-tree/",
  "Diameter of Binary Tree": "https://leetcode.com/problems/diameter-of-binary-tree/",
  "N-ary Tree Preorder Traversal": "https://leetcode.com/problems/n-ary-tree-preorder-traversal/",
  "Longest Substring Without Repeating Characters": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  "Add Two Numbers": "https://leetcode.com/problems/add-two-numbers/",
  "Container With Most Water": "https://leetcode.com/problems/container-with-most-water/",
  "3Sum": "https://leetcode.com/problems/3sum/",
  "Letter Combinations of a Phone Number": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
  "Valid Sudoku": "https://leetcode.com/problems/valid-sudoku/",
  "Group Anagrams": "https://leetcode.com/problems/group-anagrams/",
  "Maximum Product Subarray": "https://leetcode.com/problems/maximum-product-subarray/",
  "Find Minimum in Rotated Sorted Array": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
  "Binary Tree Level Order Traversal": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  "Clone Graph": "https://leetcode.com/problems/clone-graph/",
  "Course Schedule": "https://leetcode.com/problems/course-schedule/",
  "Implement Trie": "https://leetcode.com/problems/implement-trie-prefix-tree/",
  "Top K Frequent Elements": "https://leetcode.com/problems/top-k-frequent-elements/",
  "Integer to Roman": "https://leetcode.com/problems/integer-to-roman/",
  "3Sum Closest": "https://leetcode.com/problems/3sum-closest/",
  "4Sum": "https://leetcode.com/problems/4sum/",
  "Remove Nth Node From End of List": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  "Generate Parentheses": "https://leetcode.com/problems/generate-parentheses/",
  "Swap Nodes in Pairs": "https://leetcode.com/problems/swap-nodes-in-pairs/",
  "Divide Two Integers": "https://leetcode.com/problems/divide-two-integers/",
  "Next Permutation": "https://leetcode.com/problems/next-permutation/",
  "Longest Valid Parentheses": "https://leetcode.com/problems/longest-valid-parentheses/",
  "Search in Rotated Sorted Array": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
  "Find First and Last Position of Element in Sorted Array": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
  "Combination Sum": "https://leetcode.com/problems/combination-sum/",
  "Combination Sum II": "https://leetcode.com/problems/combination-sum-ii/",
  "Permutations": "https://leetcode.com/problems/permutations/",
  "Permutations II": "https://leetcode.com/problems/permutations-ii/",
  "Rotate Image": "https://leetcode.com/problems/rotate-image/",
  "Pow(x, n)": "https://leetcode.com/problems/powx-n/",
  "N-Queens II": "https://leetcode.com/problems/n-queens-ii/",
  "Jump Game": "https://leetcode.com/problems/jump-game/",
  "Merge Intervals": "https://leetcode.com/problems/merge-intervals/",
  "Insert Interval": "https://leetcode.com/problems/insert-interval/",
  "Spiral Matrix": "https://leetcode.com/problems/spiral-matrix/",
  "Unique Paths": "https://leetcode.com/problems/unique-paths/",
  "Unique Paths II": "https://leetcode.com/problems/unique-paths-ii/",
  "Minimum Path Sum": "https://leetcode.com/problems/minimum-path-sum/",
  "Set Matrix Zeroes": "https://leetcode.com/problems/set-matrix-zeroes/",
  "Search a 2D Matrix": "https://leetcode.com/problems/search-a-2d-matrix/",
  "Sort Colors": "https://leetcode.com/problems/sort-colors/",
  "Subsets": "https://leetcode.com/problems/subsets/",
  "Word Search": "https://leetcode.com/problems/word-search/",
  "Remove Duplicates from Sorted Array II": "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/",
  "Search in Rotated Sorted Array II": "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
  "Remove Duplicates from Sorted List II": "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/",
  "Partition List": "https://leetcode.com/problems/partition-list/",
  "Gray Code": "https://leetcode.com/problems/gray-code/",
  "Subsets II": "https://leetcode.com/problems/subsets-ii/",
  "Decode Ways": "https://leetcode.com/problems/decode-ways/",
  "Reverse Linked List II": "https://leetcode.com/problems/reverse-linked-list-ii/",
  "Restore IP Addresses": "https://leetcode.com/problems/restore-ip-addresses/",
  "Binary Tree Zigzag Level Order Traversal": "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
  "Maximum Depth of Binary Tree": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  "Construct Binary Tree from Preorder and Inorder Traversal": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
  "Construct Binary Tree from Inorder and Postorder Traversal": "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
  "Convert Sorted Array to Binary Search Tree": "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
  "Convert Sorted List to Binary Search Tree": "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/",
  "Balanced Binary Tree": "https://leetcode.com/problems/balanced-binary-tree/",
  "Minimum Depth of Binary Tree": "https://leetcode.com/problems/minimum-depth-of-binary-tree/",
  "Path Sum": "https://leetcode.com/problems/path-sum/",
  "Path Sum II": "https://leetcode.com/problems/path-sum-ii/",
  "Flatten Binary Tree to Linked List": "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
  "Distinct Subsequences": "https://leetcode.com/problems/distinct-subsequences/",
  "Populating Next Right Pointers in Each Node": "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
  "Populating Next Right Pointers in Each Node II": "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/",
  "Triangle": "https://leetcode.com/problems/triangle/",
  "Word Ladder II": "https://leetcode.com/problems/word-ladder-ii/",
  "Longest Consecutive Sequence": "https://leetcode.com/problems/longest-consecutive-sequence/",
  "Sum Root to Leaf Numbers": "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
  "Surrounded Regions": "https://leetcode.com/problems/surrounded-regions/",
  "Palindrome Partitioning": "https://leetcode.com/problems/palindrome-partitioning/",
  "Palindrome Partitioning II": "https://leetcode.com/problems/palindrome-partitioning-ii/",
  "Gas Station": "https://leetcode.com/problems/gas-station/",
  "Candy": "https://leetcode.com/problems/candy/",
  "Single Number II": "https://leetcode.com/problems/single-number-ii/",
  "Copy List with Random Pointer": "https://leetcode.com/problems/copy-list-with-random-pointer/",
  "Word Break": "https://leetcode.com/problems/word-break/",
  "Linked List Cycle II": "https://leetcode.com/problems/linked-list-cycle-ii/",
  "Reorder List": "https://leetcode.com/problems/reorder-list/",
  "LRU Cache": "https://leetcode.com/problems/lru-cache/",
  "Sort List": "https://leetcode.com/problems/sort-list/",
  "Evaluate Reverse Polish Notation": "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
  "Reverse Words in a String": "https://leetcode.com/problems/reverse-words-in-a-string/",
  "Find Peak Element": "https://leetcode.com/problems/find-peak-element/",
  "Compare Version Numbers": "https://leetcode.com/problems/compare-version-numbers/",
  "Fraction to Recurring Decimal": "https://leetcode.com/problems/fraction-to-recurring-decimal/",
  "Two Sum II - Input array is sorted": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
  "Majority Element II": "https://leetcode.com/problems/majority-element-ii/",
  "Kth Largest Element in an Array": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
  "Combination Sum III": "https://leetcode.com/problems/combination-sum-iii/",
  "Contains Duplicate III": "https://leetcode.com/problems/contains-duplicate-iii/",
  "Maximal Square": "https://leetcode.com/problems/maximal-square/",
  "Count Complete Tree Nodes": "https://leetcode.com/problems/count-complete-tree-nodes/",
  "Rectangle Area": "https://leetcode.com/problems/rectangle-area/",
  "Basic Calculator II": "https://leetcode.com/problems/basic-calculator-ii/",
  "Kth Smallest Element in a BST": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  "Number of Digit One": "https://leetcode.com/problems/number-of-digit-one/",
  "Palindromic Substrings": "https://leetcode.com/problems/palindromic-substrings/",
  "Product of Array Except Self": "https://leetcode.com/problems/product-of-array-except-self/",
  "Sliding Window Maximum": "https://leetcode.com/problems/sliding-window-maximum/",
  "Search a 2D Matrix II": "https://leetcode.com/problems/search-a-2d-matrix-ii/",
  "Different Ways to Add Parentheses": "https://leetcode.com/problems/different-ways-to-add-parentheses/",
  "Shortest Distance from All Buildings": "https://leetcode.com/problems/shortest-distance-from-all-buildings/",
  "H-Index": "https://leetcode.com/problems/h-index/",
  "H-Index II": "https://leetcode.com/problems/h-index-ii/",
  "Wiggle Sort": "https://leetcode.com/problems/wiggle-sort/",
  "Inorder Successor in BST": "https://leetcode.com/problems/inorder-successor-in-bst/",
  "Find the Duplicate Number": "https://leetcode.com/problems/find-the-duplicate-number/",
  "Game of Life": "https://leetcode.com/problems/game-of-life/",
  "Word Pattern": "https://leetcode.com/problems/word-pattern/",
  "Nim Game": "https://leetcode.com/problems/nim-game/",
  "Flip Game": "https://leetcode.com/problems/flip-game/",
  "Flip Game II": "https://leetcode.com/problems/flip-game-ii/",
  "Find Median from Data Stream": "https://leetcode.com/problems/find-median-from-data-stream/",
  "Serialize and Deserialize Binary Tree": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
  "Longest Increasing Subsequence": "https://leetcode.com/problems/longest-increasing-subsequence/",
  "Range Sum Query 2D - Immutable": "https://leetcode.com/problems/range-sum-query-2d-immutable/",
  "Range Sum Query - Mutable": "https://leetcode.com/problems/range-sum-query-mutable/",
  "Range Sum Query 2D - Mutable": "https://leetcode.com/problems/range-sum-query-2d-mutable/",
  "Best Time to Buy and Sell Stock with Cooldown": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
  "Minimum Height Trees": "https://leetcode.com/problems/minimum-height-trees/",
  "Burst Balloons": "https://leetcode.com/problems/burst-balloons/",
  "Super Ugly Number": "https://leetcode.com/problems/super-ugly-number/",
  "Count of Smaller Numbers After Self": "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
  "Remove Duplicate Letters": "https://leetcode.com/problems/remove-duplicate-letters/",
  "Maximum Product of Word Lengths": "https://leetcode.com/problems/maximum-product-of-word-lengths/",
  "Bulb Switcher": "https://leetcode.com/problems/bulb-switcher/",
  "Generalized Abbreviation": "https://leetcode.com/problems/generalized-abbreviation/",
  "Create Maximum Number": "https://leetcode.com/problems/create-maximum-number/",
  "Coin Change": "https://leetcode.com/problems/coin-change/",
  "Number of Connected Components in an Undirected Graph": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
  "Wiggle Sort II": "https://leetcode.com/problems/wiggle-sort-ii/",
  "Maximum Size Subarray Sum Equals k": "https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/",
  "Count of Range Sum": "https://leetcode.com/problems/count-of-range-sum/",
  "Odd Even Linked List": "https://leetcode.com/problems/odd-even-linked-list/",
  "Longest Increasing Path in a Matrix": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
  "Patching Array": "https://leetcode.com/problems/patching-array/",
  "Verify Preorder Serialization of a Binary Tree": "https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/",
  "Reconstruct Itinerary": "https://leetcode.com/problems/reconstruct-itinerary/",
  "Increasing Triplet Subsequence": "https://leetcode.com/problems/increasing-triplet-subsequence/",
  "Self Crossing": "https://leetcode.com/problems/self-crossing/",
  "Palindrome Pairs": "https://leetcode.com/problems/palindrome-pairs/",
  "House Robber III": "https://leetcode.com/problems/house-robber-iii/",
  "Counting Bits": "https://leetcode.com/problems/counting-bits/",
  "Nested List Weight Sum": "https://leetcode.com/problems/nested-list-weight-sum/",
  "Longest Substring with At Most K Distinct Characters": "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/",
  "Flatten Nested List Iterator": "https://leetcode.com/problems/flatten-nested-list-iterator/",
  "Integer Break": "https://leetcode.com/problems/integer-break/",
  "Moving Average from Data Stream": "https://leetcode.com/problems/moving-average-from-data-stream/",
  "Data Stream as Disjoint Intervals": "https://leetcode.com/problems/data-stream-as-disjoint-intervals/",
  "Design Phone Directory": "https://leetcode.com/problems/design-phone-directory/",
  "Insert Delete GetRandom O(1)": "https://leetcode.com/problems/insert-delete-getrandom-o1/",
  "Insert Delete GetRandom O(1) - Duplicates allowed": "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/",
  "Linked List Random Node": "https://leetcode.com/problems/linked-list-random-node/",
  "Median of Two Sorted Arrays": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
  "Regular Expression Matching": "https://leetcode.com/problems/regular-expression-matching/",
  "Merge k Sorted Lists": "https://leetcode.com/problems/merge-k-sorted-lists/",
  "Trapping Rain Water": "https://leetcode.com/problems/trapping-rain-water/",
  "N-Queens": "https://leetcode.com/problems/n-queens/",
  "Word Ladder": "https://leetcode.com/problems/word-ladder/",
  "Word Search II": "https://leetcode.com/problems/word-search-ii/",
  "Basic Calculator": "https://leetcode.com/problems/basic-calculator/",
  "Edit Distance": "https://leetcode.com/problems/edit-distance/",
  "Largest Rectangle in Histogram": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
  "Minimum Window Substring": "https://leetcode.com/problems/minimum-window-substring/",
  "Max Points on a Line": "https://leetcode.com/problems/max-points-on-a-line/",
  "Integer to English Words": "https://leetcode.com/problems/integer-to-english-words/",
  "Sudoku Solver": "https://leetcode.com/problems/sudoku-solver/",
  "Text Justification": "https://leetcode.com/problems/text-justification/",
  "Number of Islands": "https://leetcode.com/problems/number-of-islands/",
  "Reverse Nodes in k-Group": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
  "Substring with Concatenation of All Words": "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
  "Wildcard Matching": "https://leetcode.com/problems/wildcard-matching/",
  "Jump Game II": "https://leetcode.com/problems/jump-game-ii/",
  "First Missing Positive": "https://leetcode.com/problems/first-missing-positive/",
  "Binary Tree Maximum Path Sum": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
  "Word Break II": "https://leetcode.com/problems/word-break-ii/",
  "Shortest Palindrome": "https://leetcode.com/problems/shortest-palindrome/",
  "Paint House II": "https://leetcode.com/problems/paint-house-ii/",
  "Alien Dictionary": "https://leetcode.com/problems/alien-dictionary/",
  "Expression Add Operators": "https://leetcode.com/problems/expression-add-operators/",
  "Remove Invalid Parentheses": "https://leetcode.com/problems/remove-invalid-parentheses/",
  "The Skyline Problem": "https://leetcode.com/problems/the-skyline-problem/",
  "Russian Doll Envelopes": "https://leetcode.com/problems/russian-doll-envelopes/",
  "Frog Jump": "https://leetcode.com/problems/frog-jump/",
  "Stamping the Sequence": "https://leetcode.com/problems/stamping-the-sequence/",
  "Word Abbreviation": "https://leetcode.com/problems/word-abbreviation/",
  "Maximal Rectangle": "https://leetcode.com/problems/maximal-rectangle/",
  "Count Vowels Permutation": "https://leetcode.com/problems/count-vowels-permutation/",
  "Minimum Insertion Steps to Make a String Palindrome": "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
  "Stone Game III": "https://leetcode.com/problems/stone-game-iii/",
  "Number of Ways to Form a Target String Given a Dictionary": "https://leetcode.com/problems/number-of-ways-to-form-a-target-string-given-a-dictionary/",
  "Maximum Profit in Job Scheduling": "https://leetcode.com/problems/maximum-profit-in-job-scheduling/",
  "Critical Connections in a Network": "https://leetcode.com/problems/critical-connections-in-a-network/",
  "Find All People With Secret": "https://leetcode.com/problems/find-all-people-with-secret/",
  "Minimum Cost to Make at Least One Valid Path in a Grid": "https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/",
  "Number of Good Paths": "https://leetcode.com/problems/number-of-good-paths/",
  "Design a Food Rating System": "https://leetcode.com/problems/design-a-food-rating-system/",
  "Meeting Rooms III": "https://leetcode.com/problems/meeting-rooms-iii/",
  "Design Movie Rental System": "https://leetcode.com/problems/design-movie-rental-system/",
  "IPO": "https://leetcode.com/problems/ipo/",
  "Parallel Courses III": "https://leetcode.com/problems/parallel-courses-iii/",
  "Robot Collisions": "https://leetcode.com/problems/robot-collisions/",
  "Bus Routes": "https://leetcode.com/problems/bus-routes/",
  "Swim in Rising Water": "https://leetcode.com/problems/swim-in-rising-water/",
  "Minimum Number of Refueling Stops": "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
  "Minimum Falling Path Sum II": "https://leetcode.com/problems/minimum-falling-path-sum-ii/",
  "Super Egg Drop": "https://leetcode.com/problems/super-egg-drop/",
  "Maximum Gap": "https://leetcode.com/problems/maximum-gap/",
  "Dungeon Game": "https://leetcode.com/problems/dungeon-game/",
  "Binary Tree Upside Down": "https://leetcode.com/problems/binary-tree-upside-down/",
  "Read N Characters Given Read4 II - Call multiple times": "https://leetcode.com/problems/read-n-characters-given-read4-ii-call-multiple-times/",
  "Scramble String": "https://leetcode.com/problems/scramble-string/",
  "Interleaving String": "https://leetcode.com/problems/interleaving-string/",
  "Recover Binary Search Tree": "https://leetcode.com/problems/recover-binary-search-tree/",
  "Valid Number": "https://leetcode.com/problems/valid-number/",
  "Minimum Number of Taps to Open to Water a Garden": "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/",
  "Split Array Largest Sum": "https://leetcode.com/problems/split-array-largest-sum/",
  "Construct Target Array With Multiple Sums": "https://leetcode.com/problems/construct-target-array-with-multiple-sums/",
  "Maximum Performance of a Team": "https://leetcode.com/problems/maximum-performance-of-a-team/",
  "Minimum Operations to Make a Subsequence": "https://leetcode.com/problems/minimum-operations-to-make-a-subsequence/",
  "Count Ways to Make Array With Product": "https://leetcode.com/problems/count-ways-to-make-array-with-product/",
  "Building Boxes": "https://leetcode.com/problems/building-boxes/",
  "Maximum Frequency Stack": "https://leetcode.com/problems/maximum-frequency-stack/",
  "Super Palindromes": "https://leetcode.com/problems/super-palindromes/",
  "Binary Tree Cameras": "https://leetcode.com/problems/binary-tree-cameras/",
  "Vertical Order Traversal of a Binary Tree": "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
  "Number of Submatrices That Sum to Target": "https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/",
  "Prefix and Suffix Search": "https://leetcode.com/problems/prefix-and-suffix-search/",
  "Course Schedule III": "https://leetcode.com/problems/course-schedule-iii/",
  "Find K-th Smallest Pair Distance": "https://leetcode.com/problems/find-k-th-smallest-pair-distance/",
  "Design In-Memory File System": "https://leetcode.com/problems/design-in-memory-file-system/",
  "Encode String with Shortest Length": "https://leetcode.com/problems/encode-string-with-shortest-length/",
  "Concatenated Words": "https://leetcode.com/problems/concatenated-words/",
  "Optimal Account Balancing": "https://leetcode.com/problems/optimal-account-balancing/",
  "Sliding Puzzle": "https://leetcode.com/problems/sliding-puzzle/",
  "Cherry Pickup": "https://leetcode.com/problems/cherry-pickup/",
  "24 Game": "https://leetcode.com/problems/24-game/",
  "Zuma Game": "https://leetcode.com/problems/zuma-game/",
  "Freedom Trail": "https://leetcode.com/problems/freedom-trail/",
  "Poorest Rich Person": "https://leetcode.com/problems/super-washing-machines/",
  "K-th Smallest in Lexicographical Order": "https://leetcode.com/problems/k-th-smallest-in-lexicographical-order/",
  "Erect the Fence": "https://leetcode.com/problems/erect-the-fence/",
  "Minimum Unique Word Abbreviation": "https://leetcode.com/problems/minimum-unique-word-abbreviation/",
  "Sequence Reconstruction": "https://leetcode.com/problems/sequence-reconstruction/",
  "Minimum Number of K Consecutive Bit Flips": "https://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/",
  "Parse Lisp Expression": "https://leetcode.com/problems/parse-lisp-expression/",
  "Race Car": "https://leetcode.com/problems/race-car/",
  "Stickers to Spell Word": "https://leetcode.com/problems/stickers-to-spell-word/",
  "Cut Off Trees for Golf Event": "https://leetcode.com/problems/cut-off-trees-for-golf-event/",
  "Strange Printer": "https://leetcode.com/problems/strange-printer/",
  "Equal Tree Partition": "https://leetcode.com/problems/equal-tree-partition/",
  "Split BST": "https://leetcode.com/problems/split-bst/",
  "Maximum Sum of 3 Non-Overlapping Subarrays": "https://leetcode.com/problems/maximum-sum-of-3-non-overlapping-subarrays/",
  "Knight Probability in Chessboard": "https://leetcode.com/problems/knight-probability-in-chessboard/",
  "Falling Squares": "https://leetcode.com/problems/falling-squares/",
  "Number of Atoms": "https://leetcode.com/problems/number-of-atoms/",
  "Open the Lock": "https://leetcode.com/problems/open-the-lock/",
  "Cracking the Safe": "https://leetcode.com/problems/cracking-the-safe/",
  "Reaching Points": "https://leetcode.com/problems/reaching-points/",
  "Basic Calculator III": "https://leetcode.com/problems/basic-calculator-iii/",
  "Sliding Window Median": "https://leetcode.com/problems/sliding-window-median/",
  "LFU Cache": "https://leetcode.com/problems/lfu-cache/",
  "Smallest Range Covering Elements from K Lists": "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/",
  "Valid Parenthesis String": "https://leetcode.com/problems/valid-parenthesis-string/",
  "Robot Room Cleaner": "https://leetcode.com/problems/robot-room-cleaner/",
  "Shortest Subarray with Sum at Least K": "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/",
  "Maximum Average Subarray II": "https://leetcode.com/problems/maximum-average-subarray-ii/",
  "Task Scheduler": "https://leetcode.com/problems/task-scheduler/",
  "Design Twitter": "https://leetcode.com/problems/design-twitter/",
  "Rearrange String k Distance Apart": "https://leetcode.com/problems/rearrange-string-k-distance-apart/",
  "Remove Boxes": "https://leetcode.com/problems/remove-boxes/",
  "Permutation Sequence": "https://leetcode.com/problems/permutation-sequence/",
  "Unique Paths III": "https://leetcode.com/problems/unique-paths-iii/",
  "Smallest Rectangle Enclosing Black Pixels": "https://leetcode.com/problems/smallest-rectangle-enclosing-black-pixels/",
  "Design Search Autocomplete System": "https://leetcode.com/problems/design-search-autocomplete-system/",
  "Maximum XOR of Two Numbers in an Array": "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
  "N-ary Tree Postorder Traversal": "https://leetcode.com/problems/n-ary-tree-postorder-traversal/",
  "Design Excel Sum Formula": "https://leetcode.com/problems/design-excel-sum-formula/",
  "Smallest Good Base": "https://leetcode.com/problems/smallest-good-base/",
  "Redundant Connection II": "https://leetcode.com/problems/redundant-connection-ii/",
  "Maximum Length of Pair Chain": "https://leetcode.com/problems/maximum-length-of-pair-chain/",
  "Maximum Width of Binary Tree": "https://leetcode.com/problems/maximum-width-of-binary-tree/",
  "Employee Free Time": "https://leetcode.com/problems/employee-free-time/",
  "Find K Closest Elements": "https://leetcode.com/problems/find-k-closest-elements/",
  "Maximum Vacation Days": "https://leetcode.com/problems/maximum-vacation-days/",
  "Convex Polygon": "https://leetcode.com/problems/convex-polygon/",
  "Guess the Word": "https://leetcode.com/problems/guess-the-word/",
  "Number of Squareful Arrays": "https://leetcode.com/problems/number-of-squareful-arrays/",
  "Smallest Sufficient Team": "https://leetcode.com/problems/smallest-sufficient-team/",
  "Minimum Difficulty of a Job Schedule": "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/",
  "Count All Valid Pickup and Delivery Options": "https://leetcode.com/problems/count-all-valid-pickup-and-delivery-options/",
  "Minimum Number of Days to Make m Bouquets": "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
  "Probability of a Two Boxes Having The Same Number of Distinct Balls": "https://leetcode.com/problems/probability-of-a-two-boxes-having-the-same-number-of-distinct-balls/",
  "String Compression II": "https://leetcode.com/problems/string-compression-ii/",
  "Cherry Pickup II": "https://leetcode.com/problems/cherry-pickup-ii/",
  "Constrained Subsequence Sum": "https://leetcode.com/problems/constrained-subsequence-sum/",
  "Largest Multiple of Three": "https://leetcode.com/problems/largest-multiple-of-three/"
};
